### ISSUE TITLE
Manejo de coordenadas en MySQL

### ISSUE THREAD

**Issue by hros19** [hros19/CorreCaminos-management-system#1]
Según [este artículo](https://dba.stackexchange.com/questions/33410/whats-the-difference-between-pointx-y-and-geomfromtextpointx-y/33454#33454) podemos utilizar esto:
`INSERT INTO t1 (pt_col) VALUES(Point(1,2));`

Podemos intentarlo de la misma forma, en la tabla **Cliente** al tener Points recibiremos los valores de las coordenadas como números que no necesariamente deben ser enteros y los almacenados usando una sintaxis similar.

- [ ] Probar si funciona

**Comment by JoshJohnson2001** [comment]
Me parece
