### ISSUE TITLE
Arreglar diagrama de la base de datos

### ISSUE THREAD

**Issue by hros19** [hros19/CorreCaminos-management-system#3]
Hice muchos cambios en la base de datos, por lo que hay que acomodar el diagrama lógico que se encuentra en el [README](https://github.com/hros19/CorreCaminos-management-system#readme), también proponer que podemos dividir los archivos de la base de datos de modo que tengamos las tablas **MaintenanceLog**, **Vehicle** y **Driver** en un solo archivo **.puml** con el objetivo de que las tablas no se vean tan pequeñas ya que se van a tener que agregar varias.

**Comment by JoshJohnson2001** [comment]
Si eso, si lo había visto
