### ISSUE TITLE
Manejo de errores en MySQL

### ISSUE THREAD

**Issue by hros19** [hros19/CorreCaminos-management-system#5]
No lo he probado todavía pero parece una herramienta muy interesante y creo que la voy a utilizar debido a que en algunos casos retorno un mensaje normal como 'Error'. Tendré que cambiarlo.
<img width="380" alt="image" src="https://user-images.githubusercontent.com/89949216/162786045-1e4fb393-4bfa-47a2-87ec-f8dfd628115a.png">
Y este es el resultado:
<img width="550" alt="image" src="https://user-images.githubusercontent.com/89949216/162786092-d69bec1b-3c78-48d2-810b-e311ecf55e83.png">

**Comment by JoshJohnson2001** [comment]
Lo quito o le siguió dando error

**Comment by hros19** [comment]
No lo he probado todavía, cuando lo haga lo posteo acá y comento como me fue. Se ve demasiado útil, al menos es lo que quería desde hace rato, cuando veas algo así en [init.sql](https://github.com/hros19/CorreCaminos-management-system/blob/main/dbinit/init.sql) es porque en primer lugar quería hacer lo de la imagen.
`SELECT 'Fila no encontrada...' AS 'Error'`

**Comment by hros19** [comment]
Si se puede utilizar, está genial. Lo único que me falta es cambiar en todos los lugares en donde mando un mensaje 😢 
<img width="391" alt="image" src="https://user-images.githubusercontent.com/89949216/163019592-59b10d0b-8443-46e4-bd20-6d882fdcd309.png">
<img width="398" alt="image" src="https://user-images.githubusercontent.com/89949216/163019676-3fbf4487-2aad-4407-aacd-b39c4209fb4e.png">
