### ISSUE TITLE
Revisar completitud de la base de datos

### ISSUE THREAD

**Issue by hros19** [hros19/CorreCaminos-management-system#6]
Debido a los atrasos no revisé todo el documento de los requerimientos nuevamente para ver si la base de datos cumple con absolutamente todo y puede que me haya faltado algo. Si me hechas una mano con eso mientras termino el controlador estaría excelente.

**Comment by JoshJohnson2001** [comment]
Ahorita no estoy en mi casa, cuando llegó lo revisó
